services:
  db:
    image: postgres:15-alpine
    container_name: objects-transmitter-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: objects_transmitter_db
    ports:
      - '5432:5432'
    volumes:
      - objects-transmitter-db-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

volumes:
  objects-transmitter-db-data: